name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: ./gradlew test
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/checkout@v2
      - name: Instrumentation Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
  build:
    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set api key
        env:
          CHIA_EXPLORER_API_KEY: ${{ secrets.CHIA_EXPLORER_API_KEY }}
        run: echo CHIA_EXPLORER_API_KEY="\"$CHIA_EXPLORER_API_KEY\"" > ./local.properties
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.BASE_ANDROID_SIGN }}
          alias: ${{ secrets.ANDROID_SIGN_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SING_PASS }}
          keyPassword: ${{ secrets.ANDROID_SING_KEY_PASS }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt
